version: '3'
services:
  web:
    container_name: web
    build: .
    command: mix phx.server
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:10
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
